# data updater can update cve, cwe, capec and att&ck data in BASE_PATH directory.

services:
  app:
    image: kuromesi/dataupdater:v0.1
    volumes:
      - ./tmpfiles:/shared
    ports:
      - 8000:8000
    environment:
      - BASE_PATH=/shared # where the data located