# this is a client to query mongodb for cve data
# the cve data should be located in CVE_DIR

services:
  app:
    image: kuromesi/mongoclient:v0.1
    volumes:
      - ./tmpfiles:/shared
    ports:
      - 8000:8000
    environment:
      - CVE_DIR=/shared/cve
      - MONGO_URI=mongodb://mongo/
      - MONGO_PORT=27017
      - MONGO_USERNAME=root
      - MONGO_PASSWORD=example
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
   