version: '3.5'
services:
  mysql:
    image: mysql:5.5
    environment: 
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=test
    network_mode: "container:database-host"
    ipc: "container:database-host"
    pid: "container:database-host"