version: '2.2'
services:
  redis:
    image: redis:4.0.14-alpine
    network_mode: "container:web-host"
    ipc: "container:web-host"
    pid: "container:web-host"
  postgresql:
    image: postgres:11.9-alpine
    environment:
    - POSTGRES_USER=gitlab
    - POSTGRES_PASSWORD=password
    - POSTGRES_DB=gitlabhq_production
    - DB_EXTENSION=pg_trgm
    volumes:
    - ./load-extensions.sh:/docker-entrypoint-initdb.d/load-extensions.sh
    network_mode: "container:web-host"
    ipc: "container:web-host"
    pid: "container:web-host"
  gitlab:
    image: vulhub/gitlab:8.13.1
    depends_on:
    - redis
    - postgresql
    environment:
    - DEBUG=false
    - GITLAB_PORT=8080
    - GITLAB_SSH_PORT=10022
    - GITLAB_SECRETS_DB_KEY_BASE=secret-key-is-here1
    - GITLAB_SECRETS_SECRET_KEY_BASE=secret-key-is-here2
    - GITLAB_SECRETS_OTP_KEY_BASE=secret-key-is-here3
    - DB_ADAPTER=postgresql
    - DB_HOST=localhost
    - DB_USER=gitlab
    - DB_PASS=password
    - DB_NAME=gitlabhq_production
    - REDIS_HOST=localhost
    - GITLAB_ROOT_PASSWORD=vulhub123456
    network_mode: "container:web-host"
    ipc: "container:web-host"
    pid: "container:web-host"
  oracle:
    image: vulhub/weblogic:12.2.1.3-2018
    # ports:
    #   - "7001:7001"
    network_mode: "container:web-host"
    ipc: "container:web-host"
    pid: "container:web-host"
  git-shell:
    image: vulhub/git:2.12.2-with-openssh
    # ports:
    #   - "3322:22"
    network_mode: "container:web-host"
    ipc: "container:web-host"
    pid: "container:web-host"