version: '3.5'
services:
  kibana:
    image: vulhub/kibana:5.6.12
    depends_on:
      - elasticsearch
    # ports:
    #   - "5601:5601"
    network_mode: "container:monitor-host"
    ipc: "container:monitor-host"
    pid: "container:monitor-host"
  elasticsearch:
    image: vulhub/elasticsearch:5.6.16
    network_mode: "container:monitor-host"
    ipc: "container:monitor-host"
    pid: "container:monitor-host"
  phpmyadmin:
    image: vulhub/phpmyadmin:4.4.15.6
    volumes:
      - ./config.inc.php:/var/www/html/config.inc.php
    # ports:
    #   - "8080:80"
    network_mode: "container:monitor-host"
    ipc: "container:monitor-host"
    pid: "container:monitor-host"