version: '3.5'
services:
  pause:
    container_name: networks
    image: gcr.io/google_containers/pause-amd64:3.0
    networks:
      - work-net
      - dmz-net
      - scada-net
networks:
  work-net:
    driver: bridge
    name: work-net
    ipam:
      config:
      - subnet: 10.150.0.0/24
  dmz-net:
    driver: bridge
    name: dmz-net
    ipam:
      config:
      - subnet: 10.150.1.0/24
  scada-net:
    driver: bridge
    name: scada-net
    ipam:
      config:
      - subnet: 10.150.2.0/24